### ISSUE TITLE
Support for Vue

### ISSUE THREAD

**Issue by Stegosource** [johanholmerin/style9#12]
Hey, this looks great! I wanted to build something like this myself, but this looks like just what I need. However, I use Vue. Any chance you are going to support it? Seems like it should be doable since Vue let's you modify the webpack config, but Im not sure exactly what I need to modify.

**Comment by johanholmerin** [comment]
I made an example repo for you: [style9-vue-example](https://github.com/johanholmerin/style9-vue-example). If you check the latest commit you can see how to add style9.

**Comment by Stegosource** [comment]
Seems to have to it working. Thanks so much!

**Comment by Stegosource** [comment]
Hey @johanholmerin I was able to get the dev preview running with this, but it failed when trying to build for production (`npm run build`)

**Comment by johanholmerin** [comment]
The example repo works for me. What error message do you get?

**Comment by Stegosource** [comment]
Oh you're totally right. Must be something on my end then.
