### ISSUE TITLE
Docs: Getting started 

### ISSUE THREAD

**Issue by danilowoz** [johanholmerin/style9#2]
Hey @johanholmerin, pretty interesting package, but I've tried to run it in Nextjs applications and I wasn't able, I didn't get which are the exact steps to go with it. 

So my suggestion is to improve the documentation and perhaps add some use cases, or even an example, using NextJS, CRA, or whatever.

**Comment by johanholmerin** [comment]
To use it with Next.js or Gatsby you would need to use a custom webpack config and then add the plugin as per the README. I have opened an [issue](https://github.com/johanholmerin/style9/issues/3) about creating plugins, with would make this unnecessary.

CRA doesn't support plugins so you can't use this package with it.

Anything else I can improve about the documentation?

**Comment by danilowoz** [comment]
Plugins would be an awesome solution.
Let me know when I can take a look at this again, cheers!

**Comment by johanholmerin** [comment]
Next.js & Gatsby plugins have now been added

**Comment by danilowoz** [comment]
I just added Next plugin, and I also need to set the babel plugin (I don't know if it's expected), but it isn't clear to me how to use it. I was able to get the className, but style itself wasn't injected in the page. Am I missing something?

**Comment by johanholmerin** [comment]
No, you should not need to use the babel plugin. I created an example repo, [style9-nextjs-example](https://github.com/johanholmerin/style9-nextjs-example), that shows how to use it. If you look at the last commit it shows the necessary steps. Does that help?

**Comment by danilowoz** [comment]
Really awesome, works like a charm!

**Comment by johanholmerin** [comment]
Great. If you are interested I also have an [experimental babel macro](johanholmerin/style9-components.macro) that adds the styled-components API and support for inline styles.

**Comment by trangcongthanh** [comment]
So if I want to use style9 with CRA, I need to eject it or customize webpack config, right?

**Comment by johanholmerin** [comment]
Yes, it won't work with CRA. You should be able to get it to work with [react-app-rewired](https://github.com/timarney/react-app-rewired/), [rescripts](https://github.com/harrysolovay/rescripts), [craco](https://github.com/gsoft-inc/craco), or [react-scripts-rewired](https://github.com/marcopeg/create-react-app) using the Webpack setup, although I haven't tried it.
