### ISSUE TITLE
Compiled from Atlassian

### ISSUE THREAD

**Issue by Dattaya** [johanholmerin/style9#20]
Hi, is there any reason not to combine your efforts with [compiled](https://github.com/atlassian-labs/compiled) from Atlassian? They support shorthands properties, styled-components and emotion-like API, and much more. CSS extraction is currently being worked on.

**Comment by johanholmerin** [comment]
They have different goals. Compiled is React-specific, has a more complex API, and does not(yet) support extracting CSS. style9 is mainly an open-source implementation of Facebook's stylex. It can be used with any framework, has a very small API, and can only be pre-compiled.

**Comment by Dattaya** [comment]
Didn't even realize that yours was library agnostic, thanks for the answer.
