### ISSUE TITLE
Question: Scoping and Webpack

### ISSUE THREAD

**Issue by jordanjlatimer** [johanholmerin/style9#23]
I just found this repo and I'm excited about it. But I can't quite tell from README if it quite meets my needs. If it does I want to use it / contribute. I'm wondering:

 - It appears that this library has the ability to extract css on build time and put it into a separate CSS file. Is this correct?
 - Are the CSS classes scoped modularly scoped in the same way other CSS-in-JS libraries do?

**Comment by jordanjlatimer** [comment]
It appears [this](https://css-tricks.com/style9-build-time-css-in-js/) answers my first question.

**Comment by johanholmerin** [comment]
I'm happy you like it. I hope this answers your questions:

1. Yes, all CSS is extracted to a CSS file
2. Yes, the generated classes are hashed(e.g. `c1r9f2e5`) and won't conflict

I plan on improving the documentation in the near future.
