### ISSUE TITLE
border-radius

### ISSUE THREAD

**Issue by fshowalter** [johanholmerin/style9#26]
Seems like this is a prime candidate for auto-expanding. It was the second opened issue on inline-style-expand-shorthand (https://github.com/robinweser/inline-style-expand-shorthand/issues/2) but that project seems dormant. What are your thoughts on adding it here?

**Comment by johanholmerin** [comment]
It would be easier to create a PR for inline-style-expand-shorthand. Basic support should be easy, it's essentially the same as for padding. Supporting multiple radii, i.e. `border-radius: 10px 100px / 120px;` would be more complicated but not impossible.

Would you be interested in making a PR?

**Comment by johanholmerin** [comment]
Added in 0.10.13
