### ISSUE TITLE
Atomic css rule not works when component loaded as lazy

### ISSUE THREAD

**Issue by behnammodi** [johanholmerin/style9#40]
If You have a component something like this:

```jsx
import style9 from 'style9';

const styles = style9.create({
  blue: {
    color: 'blue',
  },
  red: {
    color: 'red'
  }
});

function LazyComponent() {
  return (
    <h1 className={styles('blue', true && 'red')}>I'm Lazy Component</h1>
  );
}

export default LazyComponent;
```

And before that you created this style in another component:
```js
const styles = style9.create({
  blue: {
    color: 'blue',
  },
  red: {
    color: 'red'
  }
});
```

New CSS file generated as duplicate

**Comment by johanholmerin** [comment]
Could you create a repo with a reproduction?

**Comment by behnammodi** [comment]
Yeah

**Comment by behnammodi** [comment]
@johanholmerin I sent you a invite to private repo

**Comment by johanholmerin** [comment]
The CSS files need to be concatenated to a single file. Adding the following to your webpack config fixes the issue:
```javascript
optimization: {
  splitChunks: {
    cacheGroups: {
      styles: {
        test: /\.css$/,
        chunks: 'all',
        enforce: true,
      }
    }
  }
}
```

I've updated the documentation to include this.

**Comment by behnammodi** [comment]
Why closed this issue? I added `cacheGroups` to config and it not works

**Comment by behnammodi** [comment]
Could you update https://github.com/behnammodi/style9-sample

**Comment by behnammodi** [comment]
I tested again, it works thanks 💪🏻, but i think we need ref to doc about CRA
