### ISSUE TITLE
Compress class names

### ISSUE THREAD

**Issue by TxHawks** [johanholmerin/style9#43]
Compressing the generated class names  into the shortest possible strings could be a nice optimization. 

In jest, my suggestion is to find a way to use incremental strings instead of hashes, e.g., `.a`, `.b`, etc., instead of `c1r9f2e5`, `cu2kwdz`, etc. 

This is the class name strategy used by [Fela](/robinweser/fela) and currently considered by compiled [(relevant RFC)](/atlassian-labs/compiled/issues/335).

**Comment by johanholmerin** [comment]
Added `incrementalClassnames` option in 0.10.7

**Comment by TxHawks** [comment]
Thank you!
