### ISSUE TITLE
Feature request: support nested selectors

### ISSUE THREAD

**Issue by TxHawks** [johanholmerin/style9#46]
I'd like to have a way to specify rules for nested selectors, like:
```js
style9.create({
  text: {
    color: '#333',
    '&>a': {
      color: 'blue',
    }
  },
});
```

Admittedly, this doesn't fit very well with the concept of atomic CSS. However, it is often a critical escape hatch in cases where we do not have control over the html, e.g., when dealing with text generated from markdown or wyiwg editors, and all other atomic-styling solutions I'm aware of support this feature to some degree.

**Comment by johanholmerin** [comment]
Not supporting selectors is a deliberate decision and not something that will change, as documented in [Background](https://github.com/johanholmerin/style9/blob/master/docs/Background.md). If that is something you need I suggest looking at another library.
