### ISSUE TITLE
exports throw error in non esm enviroments

### ISSUE THREAD

**Issue by ceopaludetto** [johanholmerin/style9#5]
When using SSR, export key in index.js file cause error because deps are externalized in webpack.

A build step using rollup(to provide cjs build) or a different file to commonjs envs should fix the error. 

https://github.com/johanholmerin/style9/blob/master/index.js#L28

**Comment by johanholmerin** [comment]
index.js is only distributed as a ES module. If you wish to use it in an environment where that is not supported, you have to provide your own compilation step.
