### ISSUE TITLE
Possibility to write css as template literal

### ISSUE THREAD

**Issue by vladshcherbin** [johanholmerin/style9#6]
👋  Hey, is it possible to add a way to write css as template literals?

Simple example:

```js
import stylesheet from 'style9'

const styles = stylesheet`
  .one {
    color: red;
  }
`

console.log('my class', styles('one'))
```

**Comment by vladshcherbin** [comment]
Related transformation: https://transform.tools/css-to-js

**Comment by johanholmerin** [comment]
I'm not going to include support for template literals. style9 is about defining styles, not CSS classes, and objects enables thing that are not possible with strings, like strong typing.

If you are interested in using template literals you could try using https://github.com/JakeCoxon/babel-plugin-css-to-js in combination with style9.

**Comment by vladshcherbin** [comment]
@johanholmerin thanks for suggestion, will try it.

I was trying to find any css-in-js library with simple template literal support for this and it turns out [astroturf](https://github.com/4Catalyzer/astroturf) is the best match but lacks rollup support :(

**Comment by sergiodxa** [comment]
@vladshcherbin you can try Styled Components or Emotion

**Comment by vladshcherbin** [comment]
@sergiodxa I've checked them before but didn't like styled api, just my personal preference to be zero runtime and more like css modules. Linaria and astroturf are best candidates so far but have issues unfortunately. Thanks for suggestion though 😉
