### ISSUE TITLE
Plugin does not work with next-contentlayer

### ISSUE THREAD

**Issue by liby** [johanholmerin/style9#69]
style9/next does not seem to work nice with [next-contentlayer](https://github.com/contentlayerdev/contentlayer). When the two plugins are used together, an error is thrown:
<details>
<summary>Syntax error: Support for the experimental syntax 'importAssertions' isn't currently enabled (3:43):</summary>	

```js
// next.config.js
const { withContentlayer } = require("next-contentlayer");
const withTM = require("next-transpile-modules")(["style9"]);
const withStyle9 = require("style9/next");

const nextConfig = withContentlayer({
  ...withStyle9()(withTM()),
});
module.exports = nextConfig;

# or
module.exports = withTM(withStyle9({})(withContentlayer({})));

# or 
module.exports = {
  ...withContentlayer(),
  ...withStyle9()(withTM()),
};

# or
function compose(...plugins) {
  return (options) => {
    return plugins.reduce((acc, next) => {
      return next(acc);
    }, options);
  };
}

module.exports = compose(
  withContentlayer,
  withStyle9(),
  withTM
)()

# or
module.exports = withStyle9()(compose(
  withContentlayer,
  withTM
)())
```
</details>

I have tried many solutions, all to no avail.

**Comment by johanholmerin** [comment]
It sounds like you need to enable the Babel `importAssertions` option:

```javascript
withStyle9({
  parserOptions: {
    plugins: ['typescript', 'jsx', 'importAssertions'],
  },
})
```

If the issue remains please add a repo with a reproduction

**Comment by liby** [comment]
> It sounds like you need to enable the Babel `importAssertions` option:
> 
> ```js
> withStyle9({
>   parserOptions: {
>     plugins: ['typescript', 'jsx', 'importAssertions'],
>   },
> })
> ```
> 
> If the issue remains please add a repo with a reproduction

Thank you. I tested it for a few days and it worked for me. However, it is important to note that `withStyle9` must be called on the outermost.

```
const { withContentlayer } = require("next-contentlayer");
const withTM = require("next-transpile-modules")(["style9"]);
const withStyle9 = require("style9/next");

function compose(...plugins) {
  return (options) => {
    return plugins.reduce((acc, next) => {
      return next(acc);
    }, options);
  };
}

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
};

// It works
module.exports = withStyle9({
  parserOptions: {
    plugins: ["typescript", "jsx", "importAssertions"],
  },
})(compose(withContentlayer, withTM)(nextConfig));
```

If you write as follows:
```
module.exports = compose(
  withContentlayer,
  withStyle9({
    parserOptions: {
      plugins: ["typescript", "jsx", "importAssertions"],
    },
  }),
  withTM
)(nextConfig);
```
You will see the #54.  Maybe you have any good ideas?
