### ISSUE TITLE
Conflicts when used with Geist UI

### ISSUE THREAD

**Issue by liby** [johanholmerin/style9#71]
Example: [blog/wip](https://github.com/liby/blog/tree/wip)

Description:  Cannot navigate via `onClick` event when there is Style9-related code in the component.

https://user-images.githubusercontent.com/38807139/175386251-b17cbf84-0334-4809-a9a9-8576807d97e5.mp4

**Comment by johanholmerin** [comment]
style9 does not contain any runtime code apart from the [class name resolver](https://github.com/johanholmerin/style9/blob/master/index.js). This issue is unrelated to style9
