### ISSUE TITLE
Using imported values inside the create method breaks the Webpack build

### ISSUE THREAD

**Issue by nonAlgebraic** [johanholmerin/style9#9]
Using imported values within the styles object passed to `Style9.create()` seems to break the Webpack build when using the Style9 Webpack loader.

## Steps to reproduce:
1. Clone this minimal reproduction repo I created: https://github.com/nonAlgebraic/style9-import-bug
2. Run `yarn install`
3. Run `yarn build`

## Expected result
The color value imported from `colorValue.js` ("`blue`") is applied to the `<body>`.

## Actual result
The Webpack build fails with an error:
```
SyntaxError: unknown: Could not evaluate value
  4 | const styles = style9.create({
  5 |   body: {
> 6 |     color: colorValue,
    |            ^^^^^^^^^^
  7 |   },
  8 | });
```

**Comment by johanholmerin** [comment]
Style values are evaluated using babel's `path.evaluate()`, which operates on a single file. In the future this may be expanded, but at the moment this is per design.

**Comment by amannn** [comment]
@johanholmerin In the source code of [`style-sheet`](https://github.com/giuseppeg/style-sheet), I found the usage of a function from linaria which could help to address this issue:

https://github.com/giuseppeg/style-sheet/blob/master/src/babel.js#L269-L288

Could that be a possible solution for this library?

**Comment by johanholmerin** [comment]
I'm aware of how linaria evaluates code. Not allowing fully dynamic values and instead relying on static evaluation is a conscious decision. Style9 is based on the design and philosophy of Facebook's stylex, which also does not support dynamic values: https://mobile.twitter.com/sebmck/status/1027276801372905472

**Comment by amannn** [comment]
Interesting, I didn't know that - thanks for sharing! I'd use custom values for use cases like these:

```js
import theme from './theme';

const styles = style9.create({
  root: {
    color: theme.colors.blue,
    padding: theme.space(2),
    borderRadius: theme.radius(1)
  },
  input: {
    // Contains responsive styles
    ...theme.typography.label
  }
});
```

Would you solve this with CSS custom properties? I can't quite get to the same ergonomics as the JS alternative:

```js
const styles = style9.create({
  root: {
    color: 'var(--color-blue)',
    padding: 'var(--space-2)',
    borderRadius: 'var(--space-1)',
  },
  input: {
    // If there are more properties added to the text style, like
    // `letters-spacing`, all call sites where this is used have
    // to be adjusted.,
    color: 'var(--typography-label-color)',
    fontSize: 'var(--typography-label-fontSize)',
    lineHeight: 'var(--typography-label-lineHeight)',

    // You can't use a CSS custom property within a media query
    '@media (min-width: 800px)': {
      fontSize: 'var(--typography-label-fontSize-medium)',
      lineHeight: 'var(--typography-label-lineHeight-medium)',
    }
  }
});
```

In this use case I'm using a static theme that doesn't change at runtime. Therefore you also get IE11 support for free. When you use dynamic themes, I guess you need to use CSS custom properties anyway, however I guess at least the media query has to be static.

In regards to theming I found your https://github.com/johanholmerin/style9-theme.macro repo. It looks interesting! From my current understanding, I'm a bit more in favour of a direct API as shown above though, but I guess that's a matter of preference.

Are the dynamic values a non-goal for this library?

**Comment by johanholmerin** [comment]
This is still somewhat of an open issue. Currently, using custom properties is the preferred solution. They can be used as values in media queries, just not in the media query definition itself yet. If you need IE11 support and only have one theme you could run PostCSS to inline the variable values, or you could build a simple Babel macro that reads from a file and inserts the value. Or if you use React you could use https://github.com/johanholmerin/style9-components.macro and resolve the value at runtime.

Having a way of using themes in a type safe way would be interesting, but fully dynamic values are not a goal.

**Comment by amannn** [comment]
Good point with using PostCSS for IE11 support! I understand your position, thanks for explaining!

**Comment by rodrigojcmello** [comment]
It is not because a value is dynamic that it means that it will change later. This could be made explicit in this documentation. I believe that this can even hinder the adoption of the library, as this type of "lock" is not common.

I spent a considerable amount of time until I understood that the magic is in the testASTShape, that by always cutting true it is possible to use dynamic values. As I understand it, style9-components.macro partially solves this, except that I prefer to fork the project and publish my modification rather than using the style-component syntax.

It would be so nice to have the option to leave the dynamic values with some option

**Comment by myamolane** [comment]
@rodrigojcmello could u merge style9's updates and publish a version?
